FROM python:3.12

WORKDIR /app

# Copy all files
COPY . .

# Install dependencies
RUN pip install langchain[anthropic] langgraph "langgraph-cli[inmem]" python-dotenv

# Expose port
EXPOSE 8000

# Run the app
CMD ["langgraph", "up"] 